Map<String, String> countryCodes = {
  'Afghanistan': 'AF',
  'Albania': 'AL',
  'Algeria': 'DZ',
  'American Samoa': 'AS',
  'Andorra': 'AD',
  'Angola': 'AO',
  'Anguilla': 'AI',
  'Antigua & Barbuda': 'AG',
  'Argentina': 'AR',
  'Armenia': 'AM',
  'Aruba': 'AW',
  'Australia': 'AU',
  'Austria': 'AT',
  'Azerbaijan': 'AZ',
  'Bahamas': 'BS',
  'Bahrain': 'BH',
  'Bangladesh': 'BD',
  'Barbados': 'BB',
  'Belarus': 'BY',
  'Belgium': 'BE',
  'Belize': 'BZ',
  'Benin': 'BJ',
  'Bermuda': 'BM',
  'Bhutan': 'BT',
  'Bolivia': 'BO',
  'Bosnia & Herzegovina': 'BA',
  'Botswana': 'BW',
  'Brazil': 'BR',
  'British Indian Ocean Territory': 'IO',
  'British Virgin Islands': 'VG',
  'Brunei': 'BN',
  'Bulgaria': 'BG',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cambodia': 'KH',
  'Cameroon': 'CM',
  'Canada': 'CA',
  'Cape Verde': 'CV',
  'Caribbean Netherlands': 'BQ',
  'Cayman Islands': 'KY',
  'Central African Republic': 'CF',
  'Chad': 'TD',
  'Chile': 'CL',
  'China': 'CN',
  'Colombia': 'CO',
  'Comoros': 'KM',
  'Congo - Brazzaville': 'CG',
  'Congo - Kinshasa': 'CD',
  'Cook Islands': 'CK',
  'Costa Rica': 'CR',
  'Côte d’Ivoire': 'CI',
  'Croatia': 'HR',
  'Cuba': 'CU',
  'Curaçao': 'CW',
  'Cyprus': 'CY',
  'Czechia': 'CZ',
  'Denmark': 'DK',
  'Djibouti': 'DJ',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'Ecuador': 'EC',
  'Egypt': 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  'Eritrea': 'ER',
  'Estonia': 'EE',
  'Eswatini': 'SZ',
  'Ethiopia': 'ET',
  'Falkland Islands (Islas Malvinas)': 'FK',
  'Faroe Islands': 'FO',
  'Fiji': 'FJ',
  'Finland': 'FI',
  'France': 'FR',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'Gabon': 'GA',
  'Gambia': 'GM',
  'Georgia': 'GE',
  'Germany': 'DE',
  'Ghana': 'GH',
  'Gibraltar': 'GI',
  'Greece': 'GR',
  'Greenland': 'GL',
  'Grenada': 'GD',
  'Guadeloupe': 'GP',
  'Guam': 'GU',
  'Guatemala': 'GT',
  'Guinea': 'GN',
  'Guinea-Bissau': 'GW',
  'Guyana': 'GY',
  'Haiti': 'HT',
  'Honduras': 'HN',
  'Hong Kong': 'HK',
  'Hungary': 'HU',
  'Iceland': 'IS',
  'India': 'IN',
  'Indonesia': 'ID',
  'Iran': 'IR',
  'Iraq': 'IQ',
  'Ireland': 'IE',
  'Israel': 'IL',
  'Italy': 'IT',
  'Jamaica': 'JM',
  'Japan': 'JP',
  'Jordan': 'JO',
  'Kazakhstan': 'KZ',
  'Kenya': 'KE',
  'Kiribati': 'KI',
  'Kosovo': 'XK',
  'Kuwait': 'KW',
  'Kyrgyzstan': 'KG',
  'Laos': 'LA',
  'Latvia': 'LV',
  'Lebanon': 'LB',
  'Lesotho': 'LS',
  'Liberia': 'LR',
  'Libya': 'LY',
  'Liechtenstein': 'LI',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Macao': 'MO',
  'Madagascar': 'MG',
  'Malawi': 'MW',
  'Malaysia': 'MY',
  'Maldives': 'MV',
  'Mali': 'ML',
  'Malta': 'MT',
  'Marshall Islands': 'MH',
  'Martinique': 'MQ',
  'Mauritania': 'MR',
  'Mauritius': 'MU',
  'Mexico': 'MX',
  'Micronesia': 'FM',
  'Moldova': 'MD',
  'Monaco': 'MC',
  'Mongolia': 'MN',
  'Montenegro': 'ME',
  'Montserrat': 'MS',
  'Morocco': 'MA',
  'Mozambique': 'MZ',
  'Myanmar (Burma)': 'MM',
  'Namibia': 'NA',
  'Nauru': 'NR',
  'Nepal': 'NP',
  'Netherlands': 'NL',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  'Nicaragua': 'NI',
  'Niger': 'NE',
  'Nigeria': 'NG',
  'Niue': 'NU',
  'Norfolk Island': 'NF',
  'North Korea': 'KP',
  'North Macedonia': 'MK',
  'Northern Mariana Islands': 'MP',
  'Norway': 'NO',
  'Oman': 'OM',
  'Pakistan': 'PK',
  'Palau': 'PW',
  'Palestine': 'PS',
  'Panama': 'PA',
  'Papua New Guinea': 'PG',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Philippines': 'PH',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Puerto Rico': 'PR',
  'Qatar': 'QA',
  'Reunion': 'RE',
  'Romania': 'RO',
  'Russia': 'RU',
  'Rwanda': 'RW',
  'Samoa': 'WS',
  'San Marino': 'SM',
  'São Tomé & Príncipe': 'ST',
  'Saudi Arabia': 'SA',
  'Senegal': 'SN',
  'Serbia': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapore': 'SG',
  'Sint Maarten': 'SX',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Solomon Islands': 'SB',
  'Somalia': 'SO',
  'South Africa': 'ZA',
  'South Korea': 'KR',
  'South Sudan': 'SS',
  'Spain': 'ES',
  'Sri Lanka': 'LK',
  'St. Barthélemy': 'BL',
  'St. Helena': 'SH',
  'St. Kitts & Nevis': 'KN',
  'St. Lucia': 'LC',
  'St. Martin': 'MF',
  'St. Pierre & Miquelon': 'PM',
  'St. Vincent & Grenadines': 'VC',
  'Sudan': 'SD',
  'Suriname': 'SR',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Syria': 'SY',
  'Taiwan': 'TW',
  'Tajikistan': 'TJ',
  'Tanzania': 'TZ',
  'Thailand': 'TH',
  'Timor-Leste': 'TL',
  'Togo': 'TG',
  'Tokelau': 'TK',
  'Tonga': 'TO',
  'Trinidad & Tobago': 'TT',
  'Tunisia': 'TN',
  'Türkiye': 'TR',
  'Turkmenistan': 'TM',
  'Turks & Caicos Islands': 'TC',
  'Tuvalu': 'TV',
  'U.S. Virgin Islands': 'VI',
  'Uganda': 'UG',
  'Ukraine': 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Vanuatu': 'VU',
  'Vatican City': 'VA',
  'Venezuela': 'VE',
  'Vietnam': 'VN',
  'Wallis & Futuna': 'WF',
  'Yemen': 'YE',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW'
};

Map<String, String> countryLanguages = {
  "Afghanistan": "Pashto",
  "Albania": "Albanian",
  "Algeria": "Arabic",
  "Andorra": "Catalan",
  "Angola": "Portuguese",
  "Antigua and Barbuda": "English",
  "Argentina": "Spanish",
  "Armenia": "Armenian",
  "Australia": "English",
  "Austria": "German",
  "Azerbaijan": "Azerbaijani",
  "Bahamas": "English",
  "Bahrain": "Arabic",
  "Bangladesh": "Bengali",
  "Barbados": "English",
  "Belarus": "Belarusian",
  "Belgium": "Dutch",
  "Belize": "English",
  "Benin": "French",
  "Bhutan": "Dzongkha",
  "Bolivia": "Spanish",
  "Bosnia and Herzegovina": "Bosnian",
  "Botswana": "Tswana",
  "Brazil": "Portuguese",
  "Brunei": "Malay",
  "Bulgaria": "Bulgarian",
  "Burkina Faso": "French",
  "Burundi": "Kirundi",
  "Cabo Verde": "Portuguese",
  "Cambodia": "Khmer",
  "Cameroon": "French",
  "Canada": "English",
  "Central African Republic": "French",
  "Chad": "Arabic",
  "Chile": "Spanish",
  "China": "Mandarin",
  "Colombia": "Spanish",
  "Comoros": "Comorian",
  "Congo": "French",
  "Costa Rica": "Spanish",
  "Croatia": "Croatian",
  "Cuba": "Spanish",
  "Cyprus": "Greek",
  "Czechia": "Czech",
  "Democratic Republic of the Congo": "French",
  "Denmark": "Danish",
  "Djibouti": "French",
  "Dominica": "English",
  "Dominican Republic": "Spanish",
  "Ecuador": "Spanish",
  "Egypt": "Arabic",
  "El Salvador": "Spanish",
  "Equatorial Guinea": "Spanish",
  "Eritrea": "Tigrinya",
  "Estonia": "Estonian",
  "Eswatini": "Swazi",
  "Ethiopia": "Amharic",
  "Fiji": "Fijian",
  "Finland": "Finnish",
  "France": "French",
  "Gabon": "French",
  "Gambia": "English",
  "Georgia": "Georgian",
  "Germany": "German",
  "Ghana": "English",
  "Greece": "Greek",
  "Grenada": "English",
  "Guatemala": "Spanish",
  "Guinea": "French",
  "Guinea-Bissau": "Portuguese",
  "Guyana": "English",
  "Haiti": "Haitian Creole",
  "Holy See": "Italian",
  "Honduras": "Spanish",
  "Hungary": "Hungarian",
  "Iceland": "Icelandic",
  "India": "Hindi",
  "Indonesia": "Indonesian",
  "Iran": "Persian",
  "Iraq": "Arabic",
  "Ireland": "Irish",
  "Israel": "Hebrew",
  "Italy": "Italian",
  "Jamaica": "English",
  "Japan": "Japanese",
  "Jordan": "Arabic",
  "Kazakhstan": "Kazakh",
  "Kenya": "Swahili",
  "Kiribati": "Gilbertese",
  "Kuwait": "Arabic",
  "Kyrgyzstan": "Kyrgyz",
  "Laos": "Lao",
  "Latvia": "Latvian",
  "Lebanon": "Arabic",
  "Lesotho": "Sesotho",
  "Liberia": "English",
  "Libya": "Arabic",
  "Liechtenstein": "German",
  "Lithuania": "Lithuanian",
  "Luxembourg": "Luxembourgish",
  "Madagascar": "Malagasy",
  "Malawi": "Chichewa",
  "Malaysia": "Malay",
  "Maldives": "Dhivehi",
  "Mali": "French",
  "Malta": "Maltese",
  "Marshall Islands": "Marshallese",
  "Mauritania": "Arabic",
  "Mauritius": "Mauritian Creole",
  "Mexico": "Spanish",
  "Micronesia": "English",
  "Moldova": "Romanian",
  "Monaco": "French",
  "Mongolia": "Mongolian",
  "Montenegro": "Serbian",
  "Morocco": "Arabic",
  "Mozambique": "Portuguese",
  "Myanmar": "Burmese",
  "Namibia": "English",
  "Nauru": "Nauruan",
  "Nepal": "Nepali",
  "Netherlands": "Dutch",
  "New Zealand": "English",
  "Nicaragua": "Spanish",
  "Niger": "French",
  "Nigeria": "English",
  "North Korea": "Korean",
  "North Macedonia": "Macedonian",
  "Norway": "Norwegian",
  "Oman": "Arabic",
  "Pakistan": "Urdu",
  "Palau": "Palauan",
  "Palestine State": "Arabic",
  "Panama": "Spanish",
  "Papua New Guinea": "Tok Pisin",
  "Paraguay": "Spanish",
  "Peru": "Spanish",
  "Philippines": "Filipino",
  "Poland": "Polish",
  "Portugal": "Portuguese",
  "Qatar": "Arabic",
  "Romania": "Romanian",
  "Russia": "Russian",
  "Rwanda": "Kinyarwanda",
  "Saint Kitts and Nevis": "English",
  "Saint Lucia": "English",
  "Saint Vincent and the Grenadines": "English",
  "Samoa": "Samoan",
  "San Marino": "Italian",
  "Sao Tome and Principe": "Portuguese",
  "Saudi Arabia": "Arabic",
  "Senegal": "French",
  "Serbia": "Serbian",
  "Seychelles": "Seychellois Creole",
  "Sierra Leone": "English",
  "Singapore": "English",
  "Slovakia": "Slovak",
  "Slovenia": "Slovene",
  "Solomon Islands": "English",
  "Somalia": "Somali",
  "South Africa": "Zulu",
  "South Korea": "Korean",
  "South Sudan": "English",
  "Spain": "Spanish",
  "Sri Lanka": "Sinhala",
  "Sudan": "Arabic",
  "Suriname": "Dutch",
  "Sweden": "Swedish",
  "Switzerland": "German",
  "Syria": "Arabic",
  "Tajikistan": "Tajik",
  "Tanzania": "Swahili",
  "Thailand": "Thai",
  "Timor-Leste": "Tetum",
  "Togo": "French",
  "Tonga": "Tongan",
  "Trinidad and Tobago": "English",
  "Tunisia": "Arabic",
  "Turkey": "Turkish",
  "Turkmenistan": "Turkmen",
  "Tuvalu": "Tuvaluan",
  "Uganda": "English",
  "Ukraine": "Ukrainian",
  "United Arab Emirates": "Arabic",
  "United Kingdom": "English",
  "United States of America": "English",
  "Uruguay": "Spanish",
  "Uzbekistan": "Uzbek",
  "Vanuatu": "Bislama",
  "Venezuela": "Spanish",
  "Vietnam": "Vietnamese",
  "Yemen": "Arabic",
  "Zambia": "Bemba",
  "Zimbabwe": "Shona",
};

Map<String, String> countryFlags = {
  "Afghanistan": "🇦🇫",
  "Albania": "🇦🇱",
  "Algeria": "🇩🇿",
  "Andorra": "🇦🇩",
  "Angola": "🇦🇴",
  "Antigua and Barbuda": "🇦🇬",
  "Argentina": "🇦🇷",
  "Armenia": "🇦🇲",
  "Australia": "🇦🇺",
  "Austria": "🇦🇹",
  "Azerbaijan": "🇦🇿",
  "Bahamas": "🇧🇸",
  "Bahrain": "🇧🇭",
  "Bangladesh": "🇧🇩",
  "Barbados": "🇧🇧",
  "Belarus": "🇧🇾",
  "Belgium": "🇧🇪",
  "Belize": "🇧🇿",
  "Benin": "🇧🇯",
  "Bhutan": "🇧🇹",
  "Bolivia": "🇧🇴",
  "Bosnia and Herzegovina": "🇧🇦",
  "Botswana": "🇧🇼",
  "Brazil": "🇧🇷",
  "Brunei": "🇧🇳",
  "Bulgaria": "🇧🇬",
  "Burkina Faso": "🇧🇫",
  "Burundi": "🇧🇮",
  "Cabo Verde": "🇨🇻",
  "Cambodia": "🇰🇭",
  "Cameroon": "🇨🇲",
  "Canada": "🇨🇦",
  "Central African Republic": "🇨🇫",
  "Chad": "🇹🇩",
  "Chile": "🇨🇱",
  "China": "🇨🇳",
  "Colombia": "🇨🇴",
  "Comoros": "🇰🇲",
  "Congo": "🇨🇬",
  "Costa Rica": "🇨🇷",
  "Croatia": "🇭🇷",
  "Cuba": "🇨🇺",
  "Cyprus": "🇨🇾",
  "Czechia": "🇨🇿",
  "Democratic Republic of the Congo": "🇨🇩",
  "Denmark": "🇩🇰",
  "Djibouti": "🇩🇯",
  "Dominica": "🇩🇲",
  "Dominican Republic": "🇩🇴",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "El Salvador": "🇸🇻",
  "Equatorial Guinea": "🇬🇶",
  "Eritrea": "🇪🇷",
  "Estonia": "🇪🇪",
  "Eswatini": "🇸🇿",
  "Ethiopia": "🇪🇹",
  "Fiji": "🇫🇯",
  "Finland": "🇫🇮",
  "France": "🇫🇷",
  "Gabon": "🇬🇦",
  "Gambia": "🇬🇲",
  "Georgia": "🇬🇪",
  "Germany": "🇩🇪",
  "Ghana": "🇬🇭",
  "Greece": "🇬🇷",
  "Grenada": "🇬🇩",
  "Guatemala": "🇬🇹",
  "Guinea": "🇬🇳",
  "Guinea-Bissau": "🇬🇼",
  "Guyana": "🇬🇾",
  "Haiti": "🇭🇹",
  "Holy See": "🇻🇦",
  "Honduras": "🇭🇳",
  "Hungary": "🇭🇺",
  "Iceland": "🇮🇸",
  "India": "🇮🇳",
  "Indonesia": "🇮🇩",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Ireland": "🇮🇪",
  "Israel": "🇮🇱",
  "Italy": "🇮🇹",
  "Jamaica": "🇯🇲",
  "Japan": "🇯🇵",
  "Jordan": "🇯🇴",
  "Kazakhstan": "🇰🇿",
  "Kenya": "🇰🇪",
  "Kiribati": "🇰🇮",
  "Kuwait": "🇰🇼",
  "Kyrgyzstan": "🇰🇬",
  "Laos": "🇱🇦",
  "Latvia": "🇱🇻",
  "Lebanon": "🇱🇧",
  "Lesotho": "🇱🇸",
  "Liberia": "🇱🇷",
  "Libya": "🇱🇾",
  "Liechtenstein": "🇱🇮",
  "Lithuania": "🇱🇹",
  "Luxembourg": "🇱🇺",
  "Madagascar": "🇲🇬",
  "Malawi": "🇲🇼",
  "Malaysia": "🇲🇾",
  "Maldives": "🇲🇻",
  "Mali": "🇲🇱",
  "Malta": "🇲🇹",
  "Marshall Islands": "🇲🇭",
  "Mauritania": "🇲🇷",
  "Mauritius": "🇲🇺",
  "Mexico": "🇲🇽",
  "Micronesia": "🇫🇲",
  "Moldova": "🇲🇩",
  "Monaco": "🇲🇨",
  "Mongolia": "🇲🇳",
  "Montenegro": "🇲🇪",
  "Morocco": "🇲🇦",
  "Mozambique": "🇲🇿",
  "Myanmar": "🇲🇲",
  "Namibia": "🇳🇦",
  "Nauru": "🇳🇷",
  "Nepal": "🇳🇵",
  "Netherlands": "🇳🇱",
  "New Zealand": "🇳🇿",
  "Nicaragua": "🇳🇮",
  "Niger": "🇳🇪",
  "Nigeria": "🇳🇬",
  "North Korea": "🇰🇵",
  "North Macedonia": "🇲🇰",
  "Norway": "🇳🇴",
  "Oman": "🇴🇲",
  "Pakistan": "🇵🇰",
  "Palau": "🇵🇼",
  "Palestine State": "🇵🇸",
  "Panama": "🇵🇦",
  "Papua New Guinea": "🇵🇬",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Philippines": "🇵🇭",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Qatar": "🇶🇦",
  "Romania": "🇷🇴",
  "Russia": "🇷🇺",
  "Rwanda": "🇷🇼",
  "Saint Kitts and Nevis": "🇰🇳",
  "Saint Lucia": "🇱🇨",
  "Saint Vincent and the Grenadines": "🇻🇨",
  "Samoa": "🇼🇸",
  "San Marino": "🇸🇲",
  "Sao Tome and Principe": "🇸🇹",
  "Saudi Arabia": "🇸🇦",
  "Senegal": "🇸🇳",
  "Serbia": "🇷🇸",
  "Seychelles": "🇸🇨",
  "Sierra Leone": "🇸🇱",
  "Singapore": "🇸🇬",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Solomon Islands": "🇸🇧",
  "Somalia": "🇸🇴",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "South Sudan": "🇸🇸",
  "Spain": "🇪🇸",
  "Sri Lanka": "🇱🇰",
  "Sudan": "🇸🇩",
  "Suriname": "🇸🇷",
  "Sweden": "🇸🇪",
  "Switzerland": "🇨🇭",
  "Syria": "🇸🇾",
  "Tajikistan": "🇹🇯",
  "Tanzania": "🇹🇿",
  "Thailand": "🇹🇭",
  "Timor-Leste": "🇹🇱",
  "Togo": "🇹🇬",
  "Tonga": "🇹🇴",
  "Trinidad and Tobago": "🇹🇹",
  "Tunisia": "🇹🇳",
  "Turkey": "🇹🇷",
  "Turkmenistan": "🇹🇲",
  "Tuvalu": "🇹🇻",
  "Uganda": "🇺🇬",
  "Ukraine": "🇺🇦",
  "United Arab Emirates": "🇦🇪",
  "United Kingdom": "🇬🇧",
  "United States of America": "🇺🇸",
  "Uruguay": "🇺🇾",
  "Uzbekistan": "🇺🇿",
  "Vanuatu": "🇻🇺",
  "Venezuela": "🇻🇪",
  "Vietnam": "🇻🇳",
  "Yemen": "🇾🇪",
  "Zambia": "🇿🇲",
  "Zimbabwe": "🇿🇼",
};
