Map<String, String> countryCodes = {
  "Afghanistan": "AF",
  "Albania": "AL",
  "Algeria": "DZ",
  "Andorra": "AD",
  "Angola": "AO",
  "Antigua and Barbuda": "AG",
  "Argentina": "AR",
  "Armenia": "AM",
  "Australia": "AU",
  "Austria": "AT",
  "Azerbaijan": "AZ",
  "Bahamas": "BS",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Barbados": "BB",
  "Belarus": "BY",
  "Belgium": "BE",
  "Belize": "BZ",
  "Benin": "BJ",
  "Bhutan": "BT",
  "Bolivia": "BO",
  "Bosnia and Herzegovina": "BA",
  "Botswana": "BW",
  "Brazil": "BR",
  "Brunei": "BN",
  "Bulgaria": "BG",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Cabo Verde": "CV",
  "Cambodia": "KH",
  "Cameroon": "CM",
  "Canada": "CA",
  "Central African Republic": "CF",
  "Chad": "TD",
  "Chile": "CL",
  "China": "CN",
  "Colombia": "CO",
  "Comoros": "KM",
  "Congo": "CG",
  "Costa Rica": "CR",
  "Croatia": "HR",
  "Cuba": "CU",
  "Cyprus": "CY",
  "Czechia": "CZ",
  "Democratic Republic of the Congo": "CD",
  "Denmark": "DK",
  "Djibouti": "DJ",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "Ecuador": "EC",
  "Egypt": "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  "Eritrea": "ER",
  "Estonia": "EE",
  "Eswatini": "SZ",
  "Ethiopia": "ET",
  "Fiji": "FJ",
  "Finland": "FI",
  "France": "FR",
  "Gabon": "GA",
  "Gambia": "GM",
  "Georgia": "GE",
  "Germany": "DE",
  "Ghana": "GH",
  "Greece": "GR",
  "Grenada": "GD",
  "Guatemala": "GT",
  "Guinea": "GN",
  "Guinea-Bissau": "GW",
  "Guyana": "GY",
  "Haiti": "HT",
  "Holy See": "VA",
  "Honduras": "HN",
  "Hungary": "HU",
  "Iceland": "IS",
  "India": "IN",
  "Indonesia": "ID",
  "Iran": "IR",
  "Iraq": "IQ",
  "Ireland": "IE",
  "Israel": "IL",
  "Italy": "IT",
  "Jamaica": "JM",
  "Japan": "JP",
  "Jordan": "JO",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Kiribati": "KI",
  "Kuwait": "KW",
  "Kyrgyzstan": "KG",
  "Laos": "LA",
  "Latvia": "LV",
  "Lebanon": "LB",
  "Lesotho": "LS",
  "Liberia": "LR",
  "Libya": "LY",
  "Liechtenstein": "LI",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Madagascar": "MG",
  "Malawi": "MW",
  "Malaysia": "MY",
  "Maldives": "MV",
  "Mali": "ML",
  "Malta": "MT",
  "Marshall Islands": "MH",
  "Mauritania": "MR",
  "Mauritius": "MU",
  "Mexico": "MX",
  "Micronesia": "FM",
  "Moldova": "MD",
  "Monaco": "MC",
  "Mongolia": "MN",
  "Montenegro": "ME",
  "Morocco": "MA",
  "Mozambique": "MZ",
  "Myanmar": "MM",
  "Namibia": "NA",
  "Nauru": "NR",
  "Nepal": "NP",
  "Netherlands": "NL",
  "New Zealand": "NZ",
  "Nicaragua": "NI",
  "Niger": "NE",
  "Nigeria": "NG",
  "North Korea": "KP",
  "North Macedonia": "MK",
  "Norway": "NO",
  "Oman": "OM",
  "Pakistan": "PK",
  "Palau": "PW",
  "Palestine State": "PS",
  "Panama": "PA",
  "Papua New Guinea": "PG",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippines": "PH",
  "Poland": "PL",
  "Portugal": "PT",
  "Qatar": "QA",
  "Romania": "RO",
  "Russia": "RU",
  "Rwanda": "RW",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Samoa": "WS",
  "San Marino": "SM",
  "Sao Tome and Principe": "ST",
  "Saudi Arabia": "SA",
  "Senegal": "SN",
  "Serbia": "RS",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Singapore": "SG",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Solomon Islands": "SB",
  "Somalia": "SO",
  "South Africa": "ZA",
  "South Korea": "KR",
  "South Sudan": "SS",
  "Spain": "ES",
  "Sri Lanka": "LK",
  "Sudan": "SD",
  "Suriname": "SR",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Syria": "SY",
  "Tajikistan": "TJ",
  "Tanzania": "TZ",
  "Thailand": "TH",
  "Timor-Leste": "TL",
  "Togo": "TG",
  "Tonga": "TO",
  "Trinidad and Tobago": "TT",
  "Tunisia": "TN",
  "Turkey": "TR",
  "Turkmenistan": "TM",
  "Tuvalu": "TV",
  "Uganda": "UG",
  "Ukraine": "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States of America": "US",
  "Uruguay": "UY",
  "Uzbekistan": "UZ",
  "Vanuatu": "VU",
  "Venezuela": "VE",
  "Vietnam": "VN",
  "Yemen": "YE",
  "Zambia": "ZM",
  "Zimbabwe": "ZW",
};

Map<String, String> countryLanguages = {
  "Afghanistan": "Pashto",
  "Albania": "Albanian",
  "Algeria": "Arabic",
  "Andorra": "Catalan",
  "Angola": "Portuguese",
  "Antigua and Barbuda": "English",
  "Argentina": "Spanish",
  "Armenia": "Armenian",
  "Australia": "English",
  "Austria": "German",
  "Azerbaijan": "Azerbaijani",
  "Bahamas": "English",
  "Bahrain": "Arabic",
  "Bangladesh": "Bengali",
  "Barbados": "English",
  "Belarus": "Belarusian",
  "Belgium": "Dutch",
  "Belize": "English",
  "Benin": "French",
  "Bhutan": "Dzongkha",
  "Bolivia": "Spanish",
  "Bosnia and Herzegovina": "Bosnian",
  "Botswana": "Tswana",
  "Brazil": "Portuguese",
  "Brunei": "Malay",
  "Bulgaria": "Bulgarian",
  "Burkina Faso": "French",
  "Burundi": "Kirundi",
  "Cabo Verde": "Portuguese",
  "Cambodia": "Khmer",
  "Cameroon": "French",
  "Canada": "English",
  "Central African Republic": "French",
  "Chad": "Arabic",
  "Chile": "Spanish",
  "China": "Mandarin",
  "Colombia": "Spanish",
  "Comoros": "Comorian",
  "Congo": "French",
  "Costa Rica": "Spanish",
  "Croatia": "Croatian",
  "Cuba": "Spanish",
  "Cyprus": "Greek",
  "Czechia": "Czech",
  "Democratic Republic of the Congo": "French",
  "Denmark": "Danish",
  "Djibouti": "French",
  "Dominica": "English",
  "Dominican Republic": "Spanish",
  "Ecuador": "Spanish",
  "Egypt": "Arabic",
  "El Salvador": "Spanish",
  "Equatorial Guinea": "Spanish",
  "Eritrea": "Tigrinya",
  "Estonia": "Estonian",
  "Eswatini": "Swazi",
  "Ethiopia": "Amharic",
  "Fiji": "Fijian",
  "Finland": "Finnish",
  "France": "French",
  "Gabon": "French",
  "Gambia": "English",
  "Georgia": "Georgian",
  "Germany": "German",
  "Ghana": "English",
  "Greece": "Greek",
  "Grenada": "English",
  "Guatemala": "Spanish",
  "Guinea": "French",
  "Guinea-Bissau": "Portuguese",
  "Guyana": "English",
  "Haiti": "Haitian Creole",
  "Holy See": "Italian",
  "Honduras": "Spanish",
  "Hungary": "Hungarian",
  "Iceland": "Icelandic",
  "India": "Hindi",
  "Indonesia": "Indonesian",
  "Iran": "Persian",
  "Iraq": "Arabic",
  "Ireland": "Irish",
  "Israel": "Hebrew",
  "Italy": "Italian",
  "Jamaica": "English",
  "Japan": "Japanese",
  "Jordan": "Arabic",
  "Kazakhstan": "Kazakh",
  "Kenya": "Swahili",
  "Kiribati": "Gilbertese",
  "Kuwait": "Arabic",
  "Kyrgyzstan": "Kyrgyz",
  "Laos": "Lao",
  "Latvia": "Latvian",
  "Lebanon": "Arabic",
  "Lesotho": "Sesotho",
  "Liberia": "English",
  "Libya": "Arabic",
  "Liechtenstein": "German",
  "Lithuania": "Lithuanian",
  "Luxembourg": "Luxembourgish",
  "Madagascar": "Malagasy",
  "Malawi": "Chichewa",
  "Malaysia": "Malay",
  "Maldives": "Dhivehi",
  "Mali": "French",
  "Malta": "Maltese",
  "Marshall Islands": "Marshallese",
  "Mauritania": "Arabic",
  "Mauritius": "Mauritian Creole",
  "Mexico": "Spanish",
  "Micronesia": "English",
  "Moldova": "Romanian",
  "Monaco": "French",
  "Mongolia": "Mongolian",
  "Montenegro": "Serbian",
  "Morocco": "Arabic",
  "Mozambique": "Portuguese",
  "Myanmar": "Burmese",
  "Namibia": "English",
  "Nauru": "Nauruan",
  "Nepal": "Nepali",
  "Netherlands": "Dutch",
  "New Zealand": "English",
  "Nicaragua": "Spanish",
  "Niger": "French",
  "Nigeria": "English",
  "North Korea": "Korean",
  "North Macedonia": "Macedonian",
  "Norway": "Norwegian",
  "Oman": "Arabic",
  "Pakistan": "Urdu",
  "Palau": "Palauan",
  "Palestine State": "Arabic",
  "Panama": "Spanish",
  "Papua New Guinea": "Tok Pisin",
  "Paraguay": "Spanish",
  "Peru": "Spanish",
  "Philippines": "Filipino",
  "Poland": "Polish",
  "Portugal": "Portuguese",
  "Qatar": "Arabic",
  "Romania": "Romanian",
  "Russia": "Russian",
  "Rwanda": "Kinyarwanda",
  "Saint Kitts and Nevis": "English",
  "Saint Lucia": "English",
  "Saint Vincent and the Grenadines": "English",
  "Samoa": "Samoan",
  "San Marino": "Italian",
  "Sao Tome and Principe": "Portuguese",
  "Saudi Arabia": "Arabic",
  "Senegal": "French",
  "Serbia": "Serbian",
  "Seychelles": "Seychellois Creole",
  "Sierra Leone": "English",
  "Singapore": "English",
  "Slovakia": "Slovak",
  "Slovenia": "Slovene",
  "Solomon Islands": "English",
  "Somalia": "Somali",
  "South Africa": "Zulu",
  "South Korea": "Korean",
  "South Sudan": "English",
  "Spain": "Spanish",
  "Sri Lanka": "Sinhala",
  "Sudan": "Arabic",
  "Suriname": "Dutch",
  "Sweden": "Swedish",
  "Switzerland": "German",
  "Syria": "Arabic",
  "Tajikistan": "Tajik",
  "Tanzania": "Swahili",
  "Thailand": "Thai",
  "Timor-Leste": "Tetum",
  "Togo": "French",
  "Tonga": "Tongan",
  "Trinidad and Tobago": "English",
  "Tunisia": "Arabic",
  "Turkey": "Turkish",
  "Turkmenistan": "Turkmen",
  "Tuvalu": "Tuvaluan",
  "Uganda": "English",
  "Ukraine": "Ukrainian",
  "United Arab Emirates": "Arabic",
  "United Kingdom": "English",
  "United States of America": "English",
  "Uruguay": "Spanish",
  "Uzbekistan": "Uzbek",
  "Vanuatu": "Bislama",
  "Venezuela": "Spanish",
  "Vietnam": "Vietnamese",
  "Yemen": "Arabic",
  "Zambia": "Bemba",
  "Zimbabwe": "Shona",
};

